# Generated by Django 5.0.2 on 2024-02-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shoes', '0002_rename_perchase_date_my_shoes_purchase_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('star', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_shoes.my_shoes')),
            ],
        ),
    ]
