# Generated by Django 5.0.2 on 2024-02-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shoes', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='shoes',
            new_name='my_shoes',
        ),
    ]
