# Generated by Django 5.0.2 on 2024-02-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shoes', '0004_rename_shoes_review_my_shoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='my_shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_shoes.my_shoes'),
        ),
    ]
